/* nn.h : Impala interface file generated by impala */
#ifndef NN_H
#define NN_H
#include <anydsl_runtime.hpp>

#ifdef __cplusplus
extern "C" {
#endif

void hello_world(void);
void sparse_mult_test(anydsl::Array<float>*, anydsl::Array<int>*, anydsl::Array<float>*);
void create_conv_test(anydsl::Array<float>*, anydsl::Array<float>*);
uint8_t* image_kernel_test(anydsl::Array<float>*, anydsl::Array<float>*, anydsl::Array<float>*, anydsl::Array<uint8_t>*);

#ifdef __cplusplus
}
#endif

#endif /* NN_H */
